// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Album {
    "id": string;
    "title": string;
    "url": string;
    "covers": string[];

    /** Creates a new Album instance. */
    constructor($$source: Partial<Album> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("covers" in $$source)) {
            this["covers"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Album instance from a string or object.
     */
    static createFrom($$source: any = {}): Album {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("covers" in $$parsedSource) {
            $$parsedSource["covers"] = $$createField3_0($$parsedSource["covers"]);
        }
        return new Album($$parsedSource as Partial<Album>);
    }
}

export class AlbumSummary {
    "id": string;
    "name": string;
    "year": number;
    "cover"?: string;
    "group": string;

    /** Creates a new AlbumSummary instance. */
    constructor($$source: Partial<AlbumSummary> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("year" in $$source)) {
            this["year"] = 0;
        }
        if (!("group" in $$source)) {
            this["group"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AlbumSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): AlbumSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AlbumSummary($$parsedSource as Partial<AlbumSummary>);
    }
}

export class Artist {
    "id"?: string;
    "name": string;

    /** Creates a new Artist instance. */
    constructor($$source: Partial<Artist> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Artist instance from a string or object.
     */
    static createFrom($$source: any = {}): Artist {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Artist($$parsedSource as Partial<Artist>);
    }
}

export class ArtistDiscography {
    "name": string;
    "uri": string;
    "albums": AlbumSummary[];

    /** Creates a new ArtistDiscography instance. */
    constructor($$source: Partial<ArtistDiscography> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("uri" in $$source)) {
            this["uri"] = "";
        }
        if (!("albums" in $$source)) {
            this["albums"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ArtistDiscography instance from a string or object.
     */
    static createFrom($$source: any = {}): ArtistDiscography {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("albums" in $$parsedSource) {
            $$parsedSource["albums"] = $$createField2_0($$parsedSource["albums"]);
        }
        return new ArtistDiscography($$parsedSource as Partial<ArtistDiscography>);
    }
}

export class ArtistInfo {
    "name": string;
    "uri": string;
    "imageUrl"?: string;
    "tracks": Song[];

    /** Creates a new ArtistInfo instance. */
    constructor($$source: Partial<ArtistInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("uri" in $$source)) {
            this["uri"] = "";
        }
        if (!("tracks" in $$source)) {
            this["tracks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ArtistInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ArtistInfo {
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tracks" in $$parsedSource) {
            $$parsedSource["tracks"] = $$createField3_0($$parsedSource["tracks"]);
        }
        return new ArtistInfo($$parsedSource as Partial<ArtistInfo>);
    }
}

export class Page {
    "size": number;
    "offset": number;
    "total": number;
    "hasNext": boolean;

    /** Creates a new Page instance. */
    constructor($$source: Partial<Page> = {}) {
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("hasNext" in $$source)) {
            this["hasNext"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Page instance from a string or object.
     */
    static createFrom($$source: any = {}): Page {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Page($$parsedSource as Partial<Page>);
    }
}

export class Playlist {
    "songs": Song[];
    "page": Page;

    /** Creates a new Playlist instance. */
    constructor($$source: Partial<Playlist> = {}) {
        if (!("songs" in $$source)) {
            this["songs"] = [];
        }
        if (!("page" in $$source)) {
            this["page"] = (new Page());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Playlist instance from a string or object.
     */
    static createFrom($$source: any = {}): Playlist {
        const $$createField0_0 = $$createType4;
        const $$createField1_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("songs" in $$parsedSource) {
            $$parsedSource["songs"] = $$createField0_0($$parsedSource["songs"]);
        }
        if ("page" in $$parsedSource) {
            $$parsedSource["page"] = $$createField1_0($$parsedSource["page"]);
        }
        return new Playlist($$parsedSource as Partial<Playlist>);
    }
}

export class PlaylistSummary {
    "id": string;
    "name": string;
    "mosaic"?: string;
    "cover"?: string;

    /** Creates a new PlaylistSummary instance. */
    constructor($$source: Partial<PlaylistSummary> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlaylistSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): PlaylistSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlaylistSummary($$parsedSource as Partial<PlaylistSummary>);
    }
}

export class SearchResult {
    "uri": string;
    "name": string;
    "type": string;
    "coverUrl"?: string;
    "artists"?: string[];
    "ownerName"?: string;
    "trackCount"?: number;

    /** Creates a new SearchResult instance. */
    constructor($$source: Partial<SearchResult> = {}) {
        if (!("uri" in $$source)) {
            this["uri"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchResult {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("artists" in $$parsedSource) {
            $$parsedSource["artists"] = $$createField4_0($$parsedSource["artists"]);
        }
        return new SearchResult($$parsedSource as Partial<SearchResult>);
    }
}

export class Share {
    "id": string;
    "url": string;

    /** Creates a new Share instance. */
    constructor($$source: Partial<Share> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Share instance from a string or object.
     */
    static createFrom($$source: any = {}): Share {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Share($$parsedSource as Partial<Share>);
    }
}

export class Song {
    "id": string;
    "url": string;
    "name": string;
    "duration": number;
    "share": Share;
    "album": Album;
    "artists": Artist[];

    /** Creates a new Song instance. */
    constructor($$source: Partial<Song> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }
        if (!("share" in $$source)) {
            this["share"] = (new Share());
        }
        if (!("album" in $$source)) {
            this["album"] = (new Album());
        }
        if (!("artists" in $$source)) {
            this["artists"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Song instance from a string or object.
     */
    static createFrom($$source: any = {}): Song {
        const $$createField4_0 = $$createType6;
        const $$createField5_0 = $$createType7;
        const $$createField6_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("share" in $$parsedSource) {
            $$parsedSource["share"] = $$createField4_0($$parsedSource["share"]);
        }
        if ("album" in $$parsedSource) {
            $$parsedSource["album"] = $$createField5_0($$parsedSource["album"]);
        }
        if ("artists" in $$parsedSource) {
            $$parsedSource["artists"] = $$createField6_0($$parsedSource["artists"]);
        }
        return new Song($$parsedSource as Partial<Song>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = AlbumSummary.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = Song.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = Page.createFrom;
const $$createType6 = Share.createFrom;
const $$createType7 = Album.createFrom;
const $$createType8 = Artist.createFrom;
const $$createType9 = $Create.Array($$createType8);
