// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Album {
    "id": string;
    "title": string;
    "url": string;
    "covers": string[] | null;
}

export interface AlbumSummary {
    "id": string;
    "name": string;
    "year": number;
    "cover"?: string;
    "group": string;
}

export interface Artist {
    "id"?: string;
    "name": string;
}

export interface ArtistDiscography {
    "name": string;
    "uri": string;
    "albums": AlbumSummary[] | null;
}

export interface ArtistInfo {
    "name": string;
    "uri": string;
    "imageUrl"?: string;
    "tracks": Song[] | null;
}

export interface Audio {
    "url": string;
    "duration": number;
    "expireAt": number;
    "videoId": string;
}

export interface Page {
    "size": number;
    "offset": number;
    "total": number;
    "hasNext": boolean;
}

export interface Playlist {
    "name"?: string;
    "cover"?: string;
    "songs": Song[] | null;
    "page": Page;
}

export interface PlaylistSummary {
    "id": string;
    "name": string;
    "mosaic"?: string;
    "cover"?: string;
    "subtitle"?: string;
}

export interface SearchResult {
    "uri": string;
    "name": string;
    "type": string;
    "coverUrl"?: string;
    "artists"?: string[] | null;
    "ownerName"?: string;
    "trackCount"?: number;
}

export interface Share {
    "id": string;
    "url": string;
}

export interface Song {
    "id": string;
    "url": string;
    "name": string;
    "duration": number;
    "share": Share;
    "album": Album;
    "artists": Artist[] | null;
    "youtubeId"?: string;
}
