// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as music$0 from "../music/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as youtube$0 from "../services/youtube/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetAlbumTracks(uri: string): $CancellablePromise<music$0.Song[] | null> {
    return $Call.ByID(419118927, uri);
}

export function GetArtist(uri: string): $CancellablePromise<music$0.ArtistInfo> {
    return $Call.ByID(3239842779, uri);
}

export function GetArtistDiscography(uri: string): $CancellablePromise<music$0.ArtistDiscography> {
    return $Call.ByID(1355396988, uri);
}

export function GetFullPlaylist(id: string): $CancellablePromise<music$0.Playlist> {
    return $Call.ByID(2338522147, id);
}

export function GetFullPlaylistNoCache(id: string): $CancellablePromise<music$0.Playlist> {
    return $Call.ByID(1881129154, id);
}

export function GetPlaylist(id: string, page: number, size: number): $CancellablePromise<music$0.Playlist> {
    return $Call.ByID(1505077398, id, page, size);
}

export function GetSong(id: string): $CancellablePromise<music$0.Song> {
    return $Call.ByID(363768417, id);
}

export function GetUserPlaylists(user: string): $CancellablePromise<music$0.PlaylistSummary[] | null> {
    return $Call.ByID(119247114, user);
}

export function GetUserPlaylistsNoCache(user: string): $CancellablePromise<music$0.PlaylistSummary[] | null> {
    return $Call.ByID(2339901353, user);
}

export function GetYouTubeAudio(spotifyId: string, search: string): $CancellablePromise<youtube$0.Audio> {
    return $Call.ByID(997358013, spotifyId, search);
}

/**
 * OpenURL opens the URL in the system browser. On Android it uses the app's
 * native Intent.ACTION_VIEW so OAuth runs outside the WebView; on other
 * platforms the frontend opens the URL itself.
 */
export function OpenURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(3376742245, url);
}

export function RevalidateFullPlaylist(id: string): $CancellablePromise<void> {
    return $Call.ByID(647509752, id);
}

export function RevalidateUserPlaylists(user: string): $CancellablePromise<void> {
    return $Call.ByID(690355719, user);
}

export function Search(query: string, searchType: string): $CancellablePromise<music$0.SearchResult[] | null> {
    return $Call.ByID(922006544, query, searchType);
}

export function SearchYouTube(query: string): $CancellablePromise<youtube$0.Video[] | null> {
    return $Call.ByID(596564785, query);
}

export function SetYouTubeId(spotifyId: string, youtubeId: string): $CancellablePromise<void> {
    return $Call.ByID(1935377904, spotifyId, youtubeId);
}

export function SpotifyDisconnect(): $CancellablePromise<void> {
    return $Call.ByID(2816245328);
}

export function SpotifyGetStatus(): $CancellablePromise<$models.SpotifyStatus> {
    return $Call.ByID(3825970500);
}

/**
 * SpotifyLogin starts the OAuth flow. It launches a local callback server,
 * generates the auth URL pointing to it, and returns that URL. The frontend
 * should open it in the system browser. When the user completes the flow
 * in their browser, Spotify redirects to the local callback server which
 * captures the code and completes the login. SpotifyLoginAndWait blocks
 * until the flow finishes (success or timeout).
 */
export function SpotifyLogin(): $CancellablePromise<string> {
    return $Call.ByID(3058262523);
}

export function SpotifyLoginAndWait(): $CancellablePromise<void> {
    return $Call.ByID(1640819277);
}

export function SpotifyReconnect(): $CancellablePromise<void> {
    return $Call.ByID(1784184919);
}
