// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class SpotifyStatus {
    "connected": boolean;
    "user": string;

    /** Creates a new SpotifyStatus instance. */
    constructor($$source: Partial<SpotifyStatus> = {}) {
        if (!("connected" in $$source)) {
            this["connected"] = false;
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SpotifyStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): SpotifyStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SpotifyStatus($$parsedSource as Partial<SpotifyStatus>);
    }
}
