// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Video {
    "id": string;
    "title": string;
    "author"?: string;
    "channelId"?: string;
}
