// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Album {
    "id": string;
    "title": string;
    "url": string;
    "covers": string[] | null;
}

export interface AlbumSummary {
    "id": string;
    "name": string;
    "year": number;
    "cover"?: string;
    "group": string;
}

export interface Artist {
    "id"?: string;
    "name": string;
}

export interface ArtistDiscography {
    "name": string;
    "uri": string;
    "albums": AlbumSummary[] | null;
}

export interface ArtistInfo {
    "name": string;
    "uri": string;
    "imageUrl"?: string;
    "tracks": Song[] | null;
}

export interface Audio {
    "url": string;
    "duration": number;
    "expireAt": number;
    "videoId": string;
    "clientName"?: string;
}

export interface Follow {
    "id": string;
    "name": string;
    "imageUrl"?: string;
    "kind": string;
}

export interface Playlist {
    "name"?: string;
    "cover"?: string;
    "owner"?: string;
    "songs": Song[] | null;
}

export interface PlaylistSummary {
    "id": string;
    "name": string;
    "cover"?: string;
    "covers"?: string[] | null;
    "subtitle"?: string;
    "owner"?: string;
}

export interface SearchResult {
    "uri": string;
    "name": string;
    "type": string;
    "coverUrl"?: string;
    "artists"?: string[] | null;
    "ownerName"?: string;
    "trackCount"?: number;
}

export interface Share {
    "id": string;
    "url": string;
}

export interface Song {
    "id": string;
    "url": string;
    "name": string;
    "duration": number;
    "share": Share;
    "album": Album;
    "artists": Artist[] | null;
    "youtubeId"?: string;

    /**
     * Broken marks a stored reference that no longer resolves at its source.
     */
    "broken"?: boolean;
}

export interface UserProfile {
    "username": string;
    "displayName": string;
    "imageUrl"?: string;
}
