// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Audio {
    "url": string;
    "duration": number;
    "expireAt": number;
    "videoId": string;

    /** Creates a new Audio instance. */
    constructor($$source: Partial<Audio> = {}) {
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }
        if (!("expireAt" in $$source)) {
            this["expireAt"] = 0;
        }
        if (!("videoId" in $$source)) {
            this["videoId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Audio instance from a string or object.
     */
    static createFrom($$source: any = {}): Audio {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Audio($$parsedSource as Partial<Audio>);
    }
}

export class Video {
    "ID": string;
    "Title": string;

    /** Creates a new Video instance. */
    constructor($$source: Partial<Video> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("Title" in $$source)) {
            this["Title"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Video instance from a string or object.
     */
    static createFrom($$source: any = {}): Video {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Video($$parsedSource as Partial<Video>);
    }
}
