// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Audio {
    "url": string;
    "duration": number;
    "expireAt": number;
    "videoId": string;
}

export interface Video {
    "ID": string;
    "Title": string;
}
