// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as music$0 from "../music/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as rooms$0 from "../rooms/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as youtube$0 from "../services/youtube/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as update$0 from "../update/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddSongsToPlaylist(id: string, refs: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(2712034592, id, refs);
}

export function CheckUpdate(): $CancellablePromise<update$0.Info> {
    return $Call.ByID(1914456057);
}

export function ClearDiscordPresence(): $CancellablePromise<void> {
    return $Call.ByID(345571046);
}

export function ClearYouTubeCookies(): $CancellablePromise<void> {
    return $Call.ByID(438744125);
}

export function CreatePlaylist(name: string): $CancellablePromise<music$0.PlaylistSummary> {
    return $Call.ByID(3765195898, name);
}

export function DeletePlaylist(id: string): $CancellablePromise<void> {
    return $Call.ByID(1312524061, id);
}

export function DiscordEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(1914947745);
}

export function FollowUser(account: string, user: string): $CancellablePromise<void> {
    return $Call.ByID(2248055530, account, user);
}

export function GetAlbumTracks(uri: string): $CancellablePromise<music$0.Song[] | null> {
    return $Call.ByID(2388259083, uri);
}

export function GetArtist(uri: string): $CancellablePromise<music$0.ArtistInfo> {
    return $Call.ByID(3340326431, uri);
}

export function GetArtistDiscography(uri: string): $CancellablePromise<music$0.ArtistDiscography> {
    return $Call.ByID(764690128, uri);
}

export function GetFollowedUsers(account: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(2564120032, account);
}

export function GetFollowing(): $CancellablePromise<music$0.Follow[] | null> {
    return $Call.ByID(2219887719);
}

export function GetFriends(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2628846885);
}

export function GetFullPlaylist(id: string): $CancellablePromise<music$0.Playlist> {
    return $Call.ByID(3017102079, id);
}

export function GetPlaylistOrder(account: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(104727978, account);
}

export function GetPlaylists(): $CancellablePromise<music$0.PlaylistSummary[] | null> {
    return $Call.ByID(2776985747);
}

export function GetSavedPlaylists(): $CancellablePromise<music$0.PlaylistSummary[] | null> {
    return $Call.ByID(2542461862);
}

export function GetUserPlaylists(user: string): $CancellablePromise<music$0.PlaylistSummary[] | null> {
    return $Call.ByID(1067966734, user);
}

export function GetUserProfile(username: string): $CancellablePromise<music$0.UserProfile> {
    return $Call.ByID(3889322832, username);
}

export function GetYouTubeChannelInfo(channel: string): $CancellablePromise<music$0.ChannelInfo> {
    return $Call.ByID(2412343568, channel);
}

export function GetYouTubeChannelPlaylists(channel: string): $CancellablePromise<music$0.PlaylistSummary[] | null> {
    return $Call.ByID(24316739, channel);
}

export function GetYouTubeChannelVideos(channel: string): $CancellablePromise<music$0.Song[] | null> {
    return $Call.ByID(2137789196, channel);
}

export function GetYouTubeId(cacheKey: string): $CancellablePromise<string> {
    return $Call.ByID(3943685640, cacheKey);
}

/**
 * InstallUpdate downloads and swaps in the newest release, then quits so the
 * relaunch scheduled by the updater can start the new version.
 */
export function InstallUpdate(): $CancellablePromise<void> {
    return $Call.ByID(668692034);
}

export function ListRooms(): $CancellablePromise<rooms$0.Room[] | null> {
    return $Call.ByID(384387320);
}

/**
 * LogError persists a frontend-reported error to the app log so failures that
 * only surface in the UI stay diagnosable after the fact.
 */
export function LogError(message: string): $CancellablePromise<void> {
    return $Call.ByID(1136571652, message);
}

/**
 * OpenURL opens the URL in the system browser. On Android it uses the app's
 * native Intent.ACTION_VIEW so OAuth runs outside the WebView; on other
 * platforms the frontend opens the URL itself.
 */
export function OpenURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(3973583225, url);
}

/**
 * RelayOverride reports the relay pinned through RELAY_API_URL/RELAY_API_TOKEN,
 * if any. The frontend applies it over the user's saved relay so a dev build can
 * point at a local relay.
 */
export function RelayOverride(): $CancellablePromise<$models.RelayOverride> {
    return $Call.ByID(577785897);
}

export function RemoveRoom(id: string): $CancellablePromise<rooms$0.Room[] | null> {
    return $Call.ByID(1937239451, id);
}

export function RemoveSavedPlaylist(id: string): $CancellablePromise<void> {
    return $Call.ByID(3652012245, id);
}

export function RemoveSongFromPlaylist(id: string, ref: string): $CancellablePromise<void> {
    return $Call.ByID(4016821159, id, ref);
}

export function ReorderPlaylist(id: string, refs: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(793586653, id, refs);
}

export function ResolveAudio(song: music$0.Song): $CancellablePromise<music$0.Audio> {
    return $Call.ByID(1456476822, song);
}

export function RevalidateFullPlaylist(id: string): $CancellablePromise<void> {
    return $Call.ByID(3671769412, id);
}

export function RevalidateUserPlaylists(user: string): $CancellablePromise<void> {
    return $Call.ByID(771735787, user);
}

export function RevalidateYouTubeChannel(channel: string): $CancellablePromise<void> {
    return $Call.ByID(57247543, channel);
}

/**
 * SaveLogs asks the user where to save a copy of the log, so a crash report can
 * be shared. It returns the chosen path, or an empty string when the dialog is
 * dismissed.
 */
export function SaveLogs(): $CancellablePromise<string> {
    return $Call.ByID(2876203262);
}

export function SavePlaylistOrder(account: string, ids: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(1174849349, account, ids);
}

export function SaveRoom(room: rooms$0.Room): $CancellablePromise<rooms$0.Room[] | null> {
    return $Call.ByID(944735522, room);
}

export function Search(query: string, searchType: string): $CancellablePromise<music$0.SearchResult[] | null> {
    return $Call.ByID(217880892, query, searchType);
}

export function SearchYouTube(query: string): $CancellablePromise<youtube$0.Video[] | null> {
    return $Call.ByID(4098143421, query);
}

export function SearchYouTubePlaylists(query: string): $CancellablePromise<music$0.PlaylistSummary[] | null> {
    return $Call.ByID(4089111504, query);
}

export function SetDiscordEnabled(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(2965467793, enabled);
}

/**
 * SetYouTubeCookies stores the Google account cookies used to sign innertube
 * requests. Playing age-restricted videos and avoiding the bot check requires
 * it; using an account this way can get it banned by Google.
 */
export function SetYouTubeCookies(cookies: string): $CancellablePromise<void> {
    return $Call.ByID(2898265424, cookies);
}

export function SetYouTubeId(cacheKey: string, youtubeId: string): $CancellablePromise<void> {
    return $Call.ByID(965987300, cacheKey, youtubeId);
}

export function SpotifyDisconnect(): $CancellablePromise<void> {
    return $Call.ByID(3257614804);
}

export function SpotifyGetStatus(): $CancellablePromise<$models.SpotifyStatus> {
    return $Call.ByID(3794811360);
}

/**
 * SpotifyLogin starts the OAuth flow. It launches a local callback server,
 * generates the auth URL pointing to it, and returns that URL. The frontend
 * should open it in the system browser. When the user completes the flow
 * in their browser, Spotify redirects to the local callback server which
 * captures the code and completes the login. SpotifyLoginAndWait blocks
 * until the flow finishes (success or timeout).
 */
export function SpotifyLogin(): $CancellablePromise<string> {
    return $Call.ByID(2894717079);
}

export function SpotifyLoginAndWait(): $CancellablePromise<void> {
    return $Call.ByID(57797921);
}

export function SyncCheck(relayURL: string): $CancellablePromise<boolean> {
    return $Call.ByID(3718808301, relayURL);
}

export function SyncConnect(relayURL: string, room: string, role: string, token: string, password: string): $CancellablePromise<void> {
    return $Call.ByID(799230255, relayURL, room, role, token, password);
}

/**
 * SyncRoomStatus reports whether a saved room is live and how many members it
 * has, without joining it.
 */
export function SyncRoomStatus(relayURL: string, room: string, token: string): $CancellablePromise<rooms$0.RoomStatus> {
    return $Call.ByID(1137831878, relayURL, room, token);
}

export function SyncSend(payload: string): $CancellablePromise<void> {
    return $Call.ByID(111451869, payload);
}

export function SyncStop(): $CancellablePromise<void> {
    return $Call.ByID(3298596019);
}

export function UnfollowUser(account: string, user: string): $CancellablePromise<void> {
    return $Call.ByID(2753135609, account, user);
}

export function UpdateDiscordPresence(payload: string): $CancellablePromise<void> {
    return $Call.ByID(2665186794, payload);
}

export function Version(): $CancellablePromise<string> {
    return $Call.ByID(3689526796);
}

/**
 * YouTubeBrowserLogin opens a window on youtube.com so the user can sign in
 * normally; the page beacons its document.cookie back to a local listener, which
 * is stored for innertube requests. Blocks until signed in, the window is
 * closed, or it times out.
 */
export function YouTubeBrowserLogin(): $CancellablePromise<void> {
    return $Call.ByID(2263405944);
}

/**
 * YouTubeBrowserLoginSupported reports whether the in-app browser login can run.
 * On Android the WebView is a single fullscreen view owned by the Activity and
 * cannot load an external URL, so only paste and cookies.txt import work there.
 */
export function YouTubeBrowserLoginSupported(): $CancellablePromise<boolean> {
    return $Call.ByID(716896478);
}

export function YouTubeSignedIn(): $CancellablePromise<boolean> {
    return $Call.ByID(513882258);
}
