// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as music$0 from "../music/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as youtube$0 from "../services/youtube/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddYouTubePlaylist(id: string): $CancellablePromise<music$0.PlaylistSummary> {
    return $Call.ByID(2929125534, id);
}

export function GetAlbumTracks(uri: string): $CancellablePromise<music$0.Song[] | null> {
    return $Call.ByID(2388259083, uri);
}

export function GetArtist(uri: string): $CancellablePromise<music$0.ArtistInfo> {
    return $Call.ByID(3340326431, uri);
}

export function GetArtistDiscography(uri: string): $CancellablePromise<music$0.ArtistDiscography> {
    return $Call.ByID(764690128, uri);
}

export function GetFullPlaylist(id: string): $CancellablePromise<music$0.Playlist> {
    return $Call.ByID(3017102079, id);
}

export function GetFullPlaylistNoCache(id: string): $CancellablePromise<music$0.Playlist> {
    return $Call.ByID(3221186334, id);
}

export function GetSong(id: string): $CancellablePromise<music$0.Song> {
    return $Call.ByID(2619436861, id);
}

export function GetUserPlaylists(user: string): $CancellablePromise<music$0.PlaylistSummary[] | null> {
    return $Call.ByID(1067966734, user);
}

export function GetUserPlaylistsNoCache(user: string): $CancellablePromise<music$0.PlaylistSummary[] | null> {
    return $Call.ByID(882132541, user);
}

export function GetYouTubePlaylists(): $CancellablePromise<music$0.PlaylistSummary[] | null> {
    return $Call.ByID(4268478320);
}

/**
 * OpenURL opens the URL in the system browser. On Android it uses the app's
 * native Intent.ACTION_VIEW so OAuth runs outside the WebView; on other
 * platforms the frontend opens the URL itself.
 */
export function OpenURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(3973583225, url);
}

export function ReadClipboard(): $CancellablePromise<string> {
    return $Call.ByID(4227429682);
}

export function RemoveYouTubePlaylist(id: string): $CancellablePromise<void> {
    return $Call.ByID(2138005495, id);
}

export function ResolveAudio(song: music$0.Song): $CancellablePromise<music$0.Audio> {
    return $Call.ByID(1456476822, song);
}

export function RevalidateFullPlaylist(id: string): $CancellablePromise<void> {
    return $Call.ByID(3671769412, id);
}

export function RevalidateUserPlaylists(user: string): $CancellablePromise<void> {
    return $Call.ByID(771735787, user);
}

export function Search(query: string, searchType: string): $CancellablePromise<music$0.SearchResult[] | null> {
    return $Call.ByID(217880892, query, searchType);
}

export function SearchYouTube(query: string): $CancellablePromise<youtube$0.Video[] | null> {
    return $Call.ByID(4098143421, query);
}

export function SearchYouTubePlaylists(query: string): $CancellablePromise<music$0.PlaylistSummary[] | null> {
    return $Call.ByID(4089111504, query);
}

export function SetYouTubeId(cacheKey: string, youtubeId: string): $CancellablePromise<void> {
    return $Call.ByID(965987300, cacheKey, youtubeId);
}

export function SpotifyDisconnect(): $CancellablePromise<void> {
    return $Call.ByID(3257614804);
}

export function SpotifyGetStatus(): $CancellablePromise<$models.SpotifyStatus> {
    return $Call.ByID(3794811360);
}

/**
 * SpotifyLogin starts the OAuth flow. It launches a local callback server,
 * generates the auth URL pointing to it, and returns that URL. The frontend
 * should open it in the system browser. When the user completes the flow
 * in their browser, Spotify redirects to the local callback server which
 * captures the code and completes the login. SpotifyLoginAndWait blocks
 * until the flow finishes (success or timeout).
 */
export function SpotifyLogin(): $CancellablePromise<string> {
    return $Call.ByID(2894717079);
}

export function SpotifyLoginAndWait(): $CancellablePromise<void> {
    return $Call.ByID(57797921);
}

export function SpotifyReconnect(): $CancellablePromise<void> {
    return $Call.ByID(4133825283);
}

export function SyncCheck(relayURL: string): $CancellablePromise<boolean> {
    return $Call.ByID(3718808301, relayURL);
}

export function SyncConnect(relayURL: string, room: string, role: string, token: string, password: string): $CancellablePromise<void> {
    return $Call.ByID(799230255, relayURL, room, role, token, password);
}

export function SyncSend(payload: string): $CancellablePromise<void> {
    return $Call.ByID(111451869, payload);
}

export function SyncStop(): $CancellablePromise<void> {
    return $Call.ByID(3298596019);
}
