// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Relay is the endpoint the app dials: a URL and the token that relay wants.
 */
export interface Relay {
    "url": string;
    "token": string;
}

export interface SpotifyStatus {
    "connected": boolean;
    "degraded": boolean;
    "user": string;
}
