// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RelayOverride pins a relay for local testing. An empty URL means the user's
 * saved relay is used.
 */
export interface RelayOverride {
    "url": string;
    "token": string;
}

export interface SpotifyStatus {
    "connected": boolean;
    "user": string;
}
