// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../../encoding/json/models.js";

/**
 * Room is a room the user saved, with the relay it belongs to so its status
 * can be queried later. The relay token and the room password are stored
 * alongside so a saved room can be checked and rejoined without retyping them;
 * both are kept in the local key-value store in plaintext, like the relay
 * settings the app already persists.
 */
export interface Room {
    "id": string;
    "code": string;
    "relayUrl": string;
    "token": string;
    "password": string;
    "name": string;
    "savedAt": number;
}

/**
 * RoomStatus is a saved room's live state as reported by the relay. State is the
 * relay's cached now-playing playback (a Playback object), absent when the room
 * has none or the relay predates the field.
 */
export interface RoomStatus {
    "active": boolean;
    "members": number;
    "hasHost": boolean;
    "locked": boolean;
    "state"?: json$0.RawMessage;
}
