// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Room is a jam room the user saved, with the relay it belongs to so its status
 * can be queried later. The relay token and the room password are stored
 * alongside so a saved room can be checked and rejoined without retyping them;
 * both are kept in the local key-value store in plaintext, like the relay
 * settings the app already persists.
 */
export interface Room {
    "id": string;
    "code": string;
    "relayUrl": string;
    "token": string;
    "password": string;
    "name": string;
    "savedAt": number;
}
