// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RoomStatus is a saved room's live state as reported by the relay.
 */
export interface RoomStatus {
    "active": boolean;
    "members": number;
    "hasHost": boolean;
    "locked": boolean;
}
