// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../../../encoding/json/models.js";

/**
 * RoomStatus is a saved room's live state as reported by the relay. State is the
 * relay's cached now-playing playback (a Playback object), absent when the room
 * has none or the relay predates the field.
 */
export interface RoomStatus {
    "active": boolean;
    "members": number;
    "hasHost": boolean;
    "locked": boolean;
    "state"?: json$0.RawMessage;
}
