// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAlbumTracks(arg1) {
  return window['go']['app']['App']['GetAlbumTracks'](arg1);
}

export function GetArtist(arg1) {
  return window['go']['app']['App']['GetArtist'](arg1);
}

export function GetArtistDiscography(arg1) {
  return window['go']['app']['App']['GetArtistDiscography'](arg1);
}

export function GetFullPlaylist(arg1) {
  return window['go']['app']['App']['GetFullPlaylist'](arg1);
}

export function GetFullPlaylistNoCache(arg1) {
  return window['go']['app']['App']['GetFullPlaylistNoCache'](arg1);
}

export function GetPlaylist(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetPlaylist'](arg1, arg2, arg3);
}

export function GetSong(arg1) {
  return window['go']['app']['App']['GetSong'](arg1);
}

export function GetUserPlaylists(arg1) {
  return window['go']['app']['App']['GetUserPlaylists'](arg1);
}

export function GetUserPlaylistsNoCache(arg1) {
  return window['go']['app']['App']['GetUserPlaylistsNoCache'](arg1);
}

export function GetYouTubeAudio(arg1, arg2) {
  return window['go']['app']['App']['GetYouTubeAudio'](arg1, arg2);
}

export function RevalidateFullPlaylist(arg1) {
  return window['go']['app']['App']['RevalidateFullPlaylist'](arg1);
}

export function RevalidateUserPlaylists(arg1) {
  return window['go']['app']['App']['RevalidateUserPlaylists'](arg1);
}

export function Search(arg1, arg2) {
  return window['go']['app']['App']['Search'](arg1, arg2);
}

export function SearchYouTube(arg1) {
  return window['go']['app']['App']['SearchYouTube'](arg1);
}

export function SetYouTubeId(arg1, arg2) {
  return window['go']['app']['App']['SetYouTubeId'](arg1, arg2);
}

export function SpotifyDisconnect() {
  return window['go']['app']['App']['SpotifyDisconnect']();
}

export function SpotifyGetStatus() {
  return window['go']['app']['App']['SpotifyGetStatus']();
}

export function SpotifyLogin() {
  return window['go']['app']['App']['SpotifyLogin']();
}

export function SpotifyLoginAndWait() {
  return window['go']['app']['App']['SpotifyLoginAndWait']();
}

export function SpotifyReconnect() {
  return window['go']['app']['App']['SpotifyReconnect']();
}
