// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {music} from '../models';
import {youtube} from '../models';
import {app} from '../models';

export function GetAlbumTracks(arg1:string):Promise<Array<music.Song>>;

export function GetArtist(arg1:string):Promise<music.ArtistInfo>;

export function GetArtistDiscography(arg1:string):Promise<music.ArtistDiscography>;

export function GetFullPlaylist(arg1:string):Promise<music.Playlist>;

export function GetFullPlaylistNoCache(arg1:string):Promise<music.Playlist>;

export function GetPlaylist(arg1:string,arg2:number,arg3:number):Promise<music.Playlist>;

export function GetSong(arg1:string):Promise<music.Song>;

export function GetUserPlaylists(arg1:string):Promise<Array<music.PlaylistSummary>>;

export function GetUserPlaylistsNoCache(arg1:string):Promise<Array<music.PlaylistSummary>>;

export function GetYouTubeAudio(arg1:string,arg2:string):Promise<youtube.Audio>;

export function RevalidateFullPlaylist(arg1:string):Promise<void>;

export function RevalidateUserPlaylists(arg1:string):Promise<void>;

export function Search(arg1:string,arg2:string):Promise<Array<music.SearchResult>>;

export function SearchYouTube(arg1:string):Promise<Array<youtube.Video>>;

export function SetYouTubeId(arg1:string,arg2:string):Promise<void>;

export function SpotifyDisconnect():Promise<void>;

export function SpotifyGetStatus():Promise<app.SpotifyStatus>;

export function SpotifyLogin():Promise<string>;

export function SpotifyLoginAndWait():Promise<void>;

export function SpotifyReconnect():Promise<void>;
